language: objective-c
osx_image: xcode7.3

cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version

email:
on_failure: change
script:
- set -o pipefail && xcodebuild test -workspace Example/BubblesView.xcworkspace -scheme BubblesView_Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
